name: Post Daily Tweet

on:
  schedule:
    # Runs once daily at a base time, then randomizes
    - cron: '0 12 * * *'  # Noon UTC as base
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Post tweet with random delay
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          # Random delay between 0-6 hours (21600 seconds)
          DELAY=$((RANDOM % 21600))
          echo "Waiting $((DELAY / 60)) minutes before posting..."
          sleep $DELAY
          python x_bot.py